parameters: {}
environment: {}
packages:
  - name: scheduler
    shared: false
    environment: {}
    parameters: {}
    annotations: {}
    functions:
      - name: schedule
        binary: false
        main: ""
        runtime: nodejs:default
        web: true
        webSecure: false
        parameters: {}
        environment: {}
        annotations: {}
        limits: {}
